version: '3.2'
services:
    virtuoso:
        restart: always
        environment:
            - BRANCH
            - GEOSERVER_URL
            - GEOSERVER_ADMIN
            - GEOSERVER_PASSWORD
            - MAKB_SRC
        build: "./makb-virtuoso/Dockerbuild"
        ports:
            - "8080:8080"
            - "8890:8890"
            - "80:80"
#           - "2222:22"
        tty: true
#   postgresql:
#       restart: always
#       build: "./makb-postgresql/Dockerbuild"
#       ports:
#           - "5432:5432"