version: '3'
services:
    tomcat:
        build: "./makb-tomcat/Dockerbuild"
        ports:
            - "8080:8080"
    postgresql:
        build: "./makb-postgresql/Dockerbuild"
        ports:
            - "5432:5432"